//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("6688f9b4-5f2d-4fd6-aafc-3a81c84a69f1")]
[assembly: AssemblyTitle("SolrNet")]
[assembly: AssemblyDescription("SolrNet")]
[assembly: AssemblyProduct("SolrNet")]
[assembly: AssemblyCopyright("Copyright Mauricio Scheffer 2007-2016")]
[assembly: AssemblyVersion("0.5.0.1003")]
[assembly: AssemblyFileVersion("0.5.0.1003")]
[assembly: AssemblyInformationalVersion("9c64895feb4a6da57a49849867ddffe69402ed1c")]
[assembly: AssemblyDelaySign(false)]


